# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountConfirmForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from BLL.AccountsBL import accountFormBL
from Globals import globalVariables
from PyQt5 import QtCore, QtGui, QtWidgets
from Services.ImgService import image

class Ui_accountConfirmDialog(object):
    _imageCode = ''

    def setAccountConfirmFields(self, name, fatherName, cnic, mobileNo, gender, address, accountType, accountStatus, balance, imageCode ):
        self.le_name.setText(name)
        self.le_fatherName.setText(fatherName)
        self.le_cnic.setText(cnic)
        self.le_cellNo.setText(mobileNo)
        self.rb_gender.setText(gender)
        self.le_address.setText(address)
        self.le_type.setText(accountType)
        self.le_status.setText(accountStatus)
        self.le_balance.setText(balance)

        if (imageCode != ''):
            self._imageCode = imageCode
            self.lbl_image.setPixmap(image.getPixmap(imageCode))
        else:
            self.lbl_image.setPixmap(QtGui.QPixmap(globalVariables.Variables._icon+'user.png'))


    def onConfirmAccount(self):
        name = self.le_name.text()
        fatherName = self.le_fatherName.text()
        cnic = self.le_cnic.text()
        mobileNo = self.le_cellNo.text()
        gender = self.rb_gender.text()
        address = self.le_address.text()
        accountType = self.le_type.text()
        accountStatus = self.le_status.text()
        balance = self.le_balance.text()
        imageCode = self._imageCode

        accountFormBL.confirmAccount(self, name, fatherName, cnic, mobileNo, gender, address, accountType, accountStatus, balance, imageCode)






    def accountConfirmSetupUi(self, accountConfirmDialog):
        accountConfirmDialog.setObjectName("accountConfirmDialog")
        accountConfirmDialog.resize(779, 239)

        windowIcon = QtGui.QPixmap(globalVariables.Variables._icon+'logo.png')
        accountConfirmDialog.setWindowIcon(QtGui.QIcon(windowIcon))

        accountConfirmDialog.setStyleSheet(open(globalVariables.Variables._style,'r').read())
        accountConfirmDialog.setAutoFillBackground(True)

        self.accountConfirmGB = QtWidgets.QGroupBox(accountConfirmDialog)
        self.accountConfirmGB.setGeometry(QtCore.QRect(10, 0, 761, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountConfirmGB.sizePolicy().hasHeightForWidth())
        self.accountConfirmGB.setSizePolicy(sizePolicy)
        self.accountConfirmGB.setObjectName("accountConfirmGB")
        self.le_name = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_name.setEnabled(False)
        self.le_name.setGeometry(QtCore.QRect(70, 20, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        self.le_name.setObjectName("le_name")
        self.le_cnic = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_cnic.setEnabled(False)
        self.le_cnic.setGeometry(QtCore.QRect(340, 50, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cnic.sizePolicy().hasHeightForWidth())
        self.le_cnic.setSizePolicy(sizePolicy)
        self.le_cnic.setObjectName("le_cnic")
        self.le_cellNo = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_cellNo.setEnabled(False)
        self.le_cellNo.setGeometry(QtCore.QRect(70, 50, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cellNo.sizePolicy().hasHeightForWidth())
        self.le_cellNo.setSizePolicy(sizePolicy)
        self.le_cellNo.setObjectName("le_cellNo")
        self.le_address = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_address.setEnabled(False)
        self.le_address.setGeometry(QtCore.QRect(340, 110, 200, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_address.sizePolicy().hasHeightForWidth())
        self.le_address.setSizePolicy(sizePolicy)
        self.le_address.setObjectName("le_address")
        self.rb_gender = QtWidgets.QRadioButton(self.accountConfirmGB)
        self.rb_gender.setEnabled(False)
        self.rb_gender.setGeometry(QtCore.QRect(70, 80, 61, 28))
        self.rb_gender.setObjectName("rb_gender")
        self.lbl_image = QtWidgets.QLabel(self.accountConfirmGB)
        self.lbl_image.setGeometry(QtCore.QRect(550, 20, 200, 200))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap("../../../Pictures/(1 of 2) a.jpg"))
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setObjectName("lbl_image")
        self.label = QtWidgets.QLabel(self.accountConfirmGB)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_3.setGeometry(QtCore.QRect(280, 50, 59, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_5.setGeometry(QtCore.QRect(280, 110, 59, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 59, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.le_type = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_type.setEnabled(False)
        self.le_type.setGeometry(QtCore.QRect(70, 110, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_type.sizePolicy().hasHeightForWidth())
        self.le_type.setSizePolicy(sizePolicy)
        self.le_type.setObjectName("le_type")
        self.le_status = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_status.setEnabled(False)
        self.le_status.setGeometry(QtCore.QRect(70, 140, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_status.sizePolicy().hasHeightForWidth())
        self.le_status.setSizePolicy(sizePolicy)
        self.le_status.setObjectName("le_status")
        self.label_9 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_10.setGeometry(QtCore.QRect(280, 80, 59, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.le_balance = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_balance.setEnabled(False)
        self.le_balance.setGeometry(QtCore.QRect(340, 80, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_balance.sizePolicy().hasHeightForWidth())
        self.le_balance.setSizePolicy(sizePolicy)
        self.le_balance.setObjectName("le_balance")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.accountConfirmGB)
        self.buttonBox.setGeometry(QtCore.QRect(370, 190, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_6 = QtWidgets.QLabel(self.accountConfirmGB)
        self.label_6.setGeometry(QtCore.QRect(280, 20, 59, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.le_fatherName = QtWidgets.QLineEdit(self.accountConfirmGB)
        self.le_fatherName.setEnabled(False)
        self.le_fatherName.setGeometry(QtCore.QRect(340, 20, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_fatherName.sizePolicy().hasHeightForWidth())
        self.le_fatherName.setSizePolicy(sizePolicy)
        self.le_fatherName.setText("")
        self.le_fatherName.setObjectName("le_fatherName")

        self.retranslateUi(accountConfirmDialog)
        self.buttonBox.accepted.connect(self.onConfirmAccount)
        self.buttonBox.accepted.connect(accountConfirmDialog.accept)
        self.buttonBox.rejected.connect(accountConfirmDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(accountConfirmDialog)

    def retranslateUi(self, accountConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        accountConfirmDialog.setWindowTitle(_translate("accountConfirmDialog", "Account Confirm"))
        self.accountConfirmGB.setTitle(_translate("accountConfirmDialog", "Conform Account"))
        self.rb_gender.setText(_translate("accountConfirmDialog", "Gender"))
        self.label.setText(_translate("accountConfirmDialog", "Name"))
        self.label_3.setText(_translate("accountConfirmDialog", "CNIC "))
        self.label_4.setText(_translate("accountConfirmDialog", "Cell No"))
        self.label_5.setText(_translate("accountConfirmDialog", "Address"))
        self.label_8.setText(_translate("accountConfirmDialog", "Gender"))
        self.label_7.setText(_translate("accountConfirmDialog", "Status"))
        self.label_9.setText(_translate("accountConfirmDialog", "Type"))
        self.label_10.setText(_translate("accountConfirmDialog", "Balance"))
        self.label_6.setText(_translate("accountConfirmDialog", "S / O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    accountConfirmDialog = QtWidgets.QDialog()
    ui = Ui_accountConfirmDialog()
    ui.accountConfirmSetupUi(accountConfirmDialog)
    accountConfirmDialog.show()
    sys.exit(app.exec_())

