# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSchemeConformForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Globals import globalVariables
from BLL.InstallmentsBL import addSchemeBL

class Ui_schemeConformDialog(object):
    def setSchemeField(self, scheme, startDate, endDate, dueDate, installments, amount, remarks):
        self.le_scheme.setText(scheme)
        self.le_startDate.setText(startDate)
        self.le_endDate.setText(endDate)
        self.le_dueDate.setText(str(dueDate))
        self.le_installments.setText(installments)
        self.le_amount.setText(amount)
        self.te_remarks.setText(remarks)

    def confirmScheme(self):
        scheme = self.le_scheme.text()
        startDate = self.le_startDate.text()
        endDate = self.le_endDate.text()
        dueDate = self.le_dueDate.text()
        installments = self.le_installments.text()
        amount = self.le_amount.text()
        remarks = self.te_remarks.toPlainText()

        addSchemeBL.confirmAddScheme(scheme, startDate, endDate, dueDate, installments, amount, remarks)

    def schemeConformSetupUi(self, schemeConformDialog):
        schemeConformDialog.setObjectName("schemeConformDialog")
        schemeConformDialog.resize(331, 319)

        windowIcon = QtGui.QPixmap(globalVariables.Variables._icon+'logo.png')
        schemeConformDialog.setWindowIcon(QtGui.QIcon(windowIcon))

        schemeConformDialog.setStyleSheet(open(globalVariables.Variables._style,'r').read())
        schemeConformDialog.setAutoFillBackground(True)

        self.conformSchemeGB = QtWidgets.QGroupBox(schemeConformDialog)
        self.conformSchemeGB.setGeometry(QtCore.QRect(10, 0, 311, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conformSchemeGB.sizePolicy().hasHeightForWidth())
        self.conformSchemeGB.setSizePolicy(sizePolicy)
        self.conformSchemeGB.setObjectName("conformSchemeGB")
        self.le_scheme = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_scheme.setEnabled(False)
        self.le_scheme.setGeometry(QtCore.QRect(100, 20, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_scheme.sizePolicy().hasHeightForWidth())
        self.le_scheme.setSizePolicy(sizePolicy)
        self.le_scheme.setObjectName("le_scheme")
        self.le_dueDate = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_dueDate.setEnabled(False)
        self.le_dueDate.setGeometry(QtCore.QRect(100, 110, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_dueDate.sizePolicy().hasHeightForWidth())
        self.le_dueDate.setSizePolicy(sizePolicy)
        self.le_dueDate.setObjectName("le_dueDate")
        self.le_installments = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_installments.setEnabled(False)
        self.le_installments.setGeometry(QtCore.QRect(100, 140, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_installments.sizePolicy().hasHeightForWidth())
        self.le_installments.setSizePolicy(sizePolicy)
        self.le_installments.setObjectName("le_installments")
        self.le_startDate = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_startDate.setEnabled(False)
        self.le_startDate.setGeometry(QtCore.QRect(100, 50, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_startDate.sizePolicy().hasHeightForWidth())
        self.le_startDate.setSizePolicy(sizePolicy)
        self.le_startDate.setObjectName("le_startDate")
        self.label = QtWidgets.QLabel(self.conformSchemeGB)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.le_endDate = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_endDate.setEnabled(False)
        self.le_endDate.setGeometry(QtCore.QRect(100, 80, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_endDate.sizePolicy().hasHeightForWidth())
        self.le_endDate.setSizePolicy(sizePolicy)
        self.le_endDate.setObjectName("le_endDate")
        self.le_amount = QtWidgets.QLineEdit(self.conformSchemeGB)
        self.le_amount.setEnabled(False)
        self.le_amount.setGeometry(QtCore.QRect(100, 170, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_amount.sizePolicy().hasHeightForWidth())
        self.le_amount.setSizePolicy(sizePolicy)
        self.le_amount.setObjectName("le_amount")
        self.label_6 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.te_remarks = QtWidgets.QTextEdit(self.conformSchemeGB)
        self.te_remarks.setEnabled(False)
        self.te_remarks.setGeometry(QtCore.QRect(100, 200, 200, 71))
        self.te_remarks.setObjectName("te_remarks")
        self.label_7 = QtWidgets.QLabel(self.conformSchemeGB)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.conformSchemeGB)
        self.buttonBox.setGeometry(QtCore.QRect(140, 280, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(schemeConformDialog)
        self.buttonBox.accepted.connect(self.confirmScheme)
        self.buttonBox.accepted.connect(schemeConformDialog.accept)
        self.buttonBox.rejected.connect(schemeConformDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(schemeConformDialog)

    def retranslateUi(self, schemeConformDialog):
        _translate = QtCore.QCoreApplication.translate
        schemeConformDialog.setWindowTitle(_translate("schemeConformDialog", "Conform Scheme"))
        self.conformSchemeGB.setTitle(_translate("schemeConformDialog", "Conform Scheme"))
        self.label.setText(_translate("schemeConformDialog", "Scheme"))
        self.label_2.setText(_translate("schemeConformDialog", "Due Date"))
        self.label_3.setText(_translate("schemeConformDialog", "Installments"))
        self.label_4.setText(_translate("schemeConformDialog", "Start Date"))
        self.label_5.setText(_translate("schemeConformDialog", "End Date"))
        self.label_6.setText(_translate("schemeConformDialog", "Amount"))
        self.label_7.setText(_translate("schemeConformDialog", "Remarks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    schemeConformDialog = QtWidgets.QDialog()
    ui = Ui_schemeConformDialog()
    ui.schemeConformSetupUi(schemeConformDialog)
    schemeConformDialog.show()
    sys.exit(app.exec_())

