# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignSchemeForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Globals import globalVariables,globalList
from BLL.InstallmentsBL import assignSchemeBL
from Services.MiscService import dateTime

class Ui_assignSchemeWindow(object):
    _schemeID = 0
    _accountID = 0

    def init(self):
        self.setSchemeList()


    def onAccountTypeChange(self,text):
        if(self.cb_accountType.currentIndex()>0):
            self.setAccounts(text)
            self.cb_account.setFocus()

    def setAccounts(self,accountType):
        self.cb_account.clear()
        self.cb_account.addItem("",0)
        accountList = assignSchemeBL.getAccountByType(accountType)
        for id, name, mob in accountList:
            self.cb_account.addItem(mob+"-"+name,id)

    def onAccountChange(self):
        id = self.cb_account.currentData()
        if(self.cb_account.currentIndex() > 0):
            self.getSetAccountsinfo(id)
            self.showAssignedScheme(id)
            self._accountID = id
            self.cb_scheme.setFocus()
        else:
            self._accountID = 0
            self.le_name.setText('')
            self.le_fatherName.setText('')
            self.le_cnic.setText('')
            self.le_cellNo.setText('')
            self.te_address.setPlainText('')
            self.le_balance.setText('')
            self.le_status.setText('')
            self.cb_scheme.setCurrentIndex(0)
            self.le_installment.setText('')
            self.te_remarks.setPlainText('')
            self.tbl_assignScheme.setRowCount(0)
            self.tbl_assignScheme.setRowCount(18)


    def getSetAccountsinfo(self,accountID):
        accountInfoList = assignSchemeBL.getAccountInfo(accountID)
        for x in accountInfoList:
            self._accountID = x[0]
            self.le_name.setText(x[2])
            self.le_fatherName.setText(x[3])
            self.le_cnic.setText(x[5])
            self.le_cellNo.setText(x[6])
            self.te_address.setText(x[8])
            self.le_status.setText(x[11])
            self.le_balance.setText(str(x[12]))


    def setSchemeList(self):
        self.cb_scheme.clear()
        self.cb_scheme.addItem('SELECT')
        schemeList = assignSchemeBL.getSchemeList()
        for id, name, startDate, endDate, dueDate, installments, amount, remarks in schemeList:
            self.cb_scheme.addItem(name,id)


    def onSchemeChange(self):
        id = self.cb_scheme.currentData()
        if(self.cb_scheme.currentIndex() > 0):
            self.setSchemeinfo(id)
            self._schemeID = id
            self.le_installment.setFocus()
        else:
            self._schemeID = 0
            self.le_installmentAmount.setText('')
            self.le_installments.setText('')

    def setSchemeinfo(self,schemeID):
        schemeInfoList = assignSchemeBL.getSchemeInfo(schemeID)
        for x in schemeInfoList:
            self.le_installments.setText(str(x[5]))
            self.le_installmentAmount.setText(str(x[6]))

    def showAssignedScheme(self,accountId):
        result = assignSchemeBL.getAllAssignedSchemes(accountId)

        self.tbl_assignScheme.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tbl_assignScheme.insertRow(row_number)
            for colum_number, data in enumerate(row_data):
                if(colum_number == 2 or colum_number == 3):
                    self.tbl_assignScheme.setItem(row_number, colum_number, QtWidgets.QTableWidgetItem(dateTime.getDateWithoutTime(data)))
                else:
                    self.tbl_assignScheme.setItem(row_number, colum_number, QtWidgets.QTableWidgetItem(str(data)))

        if(self.tbl_assignScheme.rowCount() < 19):
            self.tbl_assignScheme.setRowCount(19)


    def onSubmit(self):
        accountID = self._accountID
        schemeID = self._schemeID
        name = self.le_name.text()
        cnic = self.le_cnic.text()
        cellno = self.le_cellNo.text()
        scheme = self.cb_scheme.currentText()
        amount = self.le_installment.text()
        remarks = self.te_remarks.toPlainText()

        assignSchemeBL.validateAssginScheme(self, accountID, schemeID, name, cnic, cellno, scheme, amount, remarks)

    def onCancel(self):
        self.cb_accountType.setCurrentIndex(0)
        self.cb_account.setCurrentIndex(0)
        self.le_name.setText('')
        self.le_fatherName.setText('')
        self.le_cnic.setText('')
        self.le_cellNo.setText('')
        self.te_address.setPlainText('')
        self.le_balance.setText('')
        self.le_status.setText('')
        self.cb_scheme.setCurrentIndex(0)
        self.le_installmentAmount.setText('')
        self.le_installments.setText('')
        self.le_installment.setText('')
        self.te_remarks.setPlainText('')
        self.tbl_assignScheme.setRowCount(0)
        self.tbl_assignScheme.setRowCount(18)



    def assignSchemeSetupUi(self, assignSchemeWindow):
        assignSchemeWindow.setObjectName("assignSchemeWindow")
        assignSchemeWindow.resize(1373, 723)

        windowIcon = QtGui.QPixmap(globalVariables.Variables._icon+'logo.png')
        assignSchemeWindow.setWindowIcon(QtGui.QIcon(windowIcon))

        assignSchemeWindow.setStyleSheet(open(globalVariables.Variables._style,'r').read())
        assignSchemeWindow.setAutoFillBackground(True)

        intRegex=QtCore.QRegExp("[0-9_]+")
        self.onlyInt = QtGui.QRegExpValidator(intRegex)

        charRegex=QtCore.QRegExp("[a-z-A-Z- -_]+")
        self.onlyChar = QtGui.QRegExpValidator(charRegex)

        self.centralwidget = QtWidgets.QWidget(assignSchemeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.assignSchemeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.assignSchemeGB.setGeometry(QtCore.QRect(10, 0, 311, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assignSchemeGB.sizePolicy().hasHeightForWidth())
        self.assignSchemeGB.setSizePolicy(sizePolicy)
        self.assignSchemeGB.setObjectName("assignSchemeGB")
        self.btn_submit = QtWidgets.QPushButton(self.assignSchemeGB)
        self.btn_submit.setGeometry(QtCore.QRect(100, 640, 100, 28))
        submitIcon = QtGui.QPixmap(globalVariables.Variables._icon+'rightIcon.png')
        self.btn_submit.setIcon(QtGui.QIcon(submitIcon))
        self.btn_submit.setObjectName("btn_submit")
        self.btn_submit.clicked.connect(self.onSubmit)
        
        self.btn_cancel = QtWidgets.QPushButton(self.assignSchemeGB)
        self.btn_cancel.setGeometry(QtCore.QRect(200, 640, 100, 28))
        cancelIcon = QtGui.QPixmap(globalVariables.Variables._icon+'cancelIcon.png')
        self.btn_cancel.setIcon(QtGui.QIcon(cancelIcon))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.clicked.connect(self.onCancel)
        
        self.label_11 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_11.setGeometry(QtCore.QRect(5, 340, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.le_balance = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_balance.setEnabled(False)
        self.le_balance.setGeometry(QtCore.QRect(100, 280, 200, 28))
        self.le_balance.setObjectName("le_balance")
        self.le_installmentAmount = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_installmentAmount.setEnabled(False)
        self.le_installmentAmount.setGeometry(QtCore.QRect(100, 370, 200, 28))
        self.le_installmentAmount.setObjectName("le_installmentAmount")
        self.te_remarks = QtWidgets.QTextEdit(self.assignSchemeGB)
        self.te_remarks.setEnabled(True)
        self.te_remarks.setGeometry(QtCore.QRect(100, 460, 200, 75))
        self.te_remarks.setObjectName("te_remarks")
        self.le_cellNo = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_cellNo.setEnabled(False)
        self.le_cellNo.setGeometry(QtCore.QRect(100, 170, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cellNo.sizePolicy().hasHeightForWidth())
        self.le_cellNo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_cellNo.setFont(font)
        self.le_cellNo.setMaxLength(11)
        self.le_cellNo.setObjectName("le_cellNo")
        self.label_12 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_12.setGeometry(QtCore.QRect(5, 280, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.le_installments = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_installments.setEnabled(False)
        self.le_installments.setGeometry(QtCore.QRect(100, 400, 200, 28))
        self.le_installments.setObjectName("le_installments")
        self.le_name = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_name.setEnabled(False)
        self.le_name.setGeometry(QtCore.QRect(100, 80, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_name.setFont(font)
        self.le_name.setMaxLength(32)
        self.le_name.setObjectName("le_name")
        self.le_cnic = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_cnic.setEnabled(False)
        self.le_cnic.setGeometry(QtCore.QRect(100, 140, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cnic.sizePolicy().hasHeightForWidth())
        self.le_cnic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_cnic.setFont(font)
        self.le_cnic.setMaxLength(13)
        self.le_cnic.setObjectName("le_cnic")
        self.cb_account = QtWidgets.QComboBox(self.assignSchemeGB)
        self.cb_account.setGeometry(QtCore.QRect(100, 50, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_account.setFont(font)
        self.cb_account.setEditable(True)
        self.cb_account.setObjectName("cb_account")
        self.cb_account.activated[str].connect(self.onAccountChange)
        
        self.label_3 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_3.setGeometry(QtCore.QRect(5, 140, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cb_scheme = QtWidgets.QComboBox(self.assignSchemeGB)
        self.cb_scheme.setGeometry(QtCore.QRect(100, 340, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_scheme.setFont(font)
        self.cb_scheme.setEditable(False)
        self.cb_scheme.setObjectName("cb_scheme")
        self.cb_scheme.activated[str].connect(self.onSchemeChange)
        
        self.label_5 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_5.setGeometry(QtCore.QRect(5, 200, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_10.setGeometry(QtCore.QRect(5, 50, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_13.setGeometry(QtCore.QRect(5, 430, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.le_installment = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_installment.setGeometry(QtCore.QRect(100, 430, 200, 28))
        self.le_installment.setObjectName("le_installment")
        self.label_4 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_4.setGeometry(QtCore.QRect(5, 170, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.te_address = QtWidgets.QTextEdit(self.assignSchemeGB)
        self.te_address.setEnabled(False)
        self.te_address.setGeometry(QtCore.QRect(100, 200, 200, 75))
        self.te_address.setObjectName("te_address")
        self.label_6 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_6.setGeometry(QtCore.QRect(5, 460, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.assignSchemeGB)
        self.label.setGeometry(QtCore.QRect(5, 80, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cb_accountType = QtWidgets.QComboBox(self.assignSchemeGB)
        self.cb_accountType.setGeometry(QtCore.QRect(100, 20, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_accountType.setFont(font)
        self.cb_accountType.setEditable(False)
        self.cb_accountType.addItem('SELECT')
        self.cb_accountType.addItems(globalList.List._accountTypeList)
        self.cb_accountType.setObjectName("cb_accountType")
        self.cb_accountType.activated[str].connect(self.onAccountTypeChange)
        
        self.label_14 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_14.setGeometry(QtCore.QRect(5, 20, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_15.setGeometry(QtCore.QRect(5, 310, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.le_status = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_status.setEnabled(False)
        self.le_status.setGeometry(QtCore.QRect(100, 310, 200, 28))
        self.le_status.setObjectName("le_status")
        self.label_2 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_2.setGeometry(QtCore.QRect(5, 110, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.le_fatherName = QtWidgets.QLineEdit(self.assignSchemeGB)
        self.le_fatherName.setEnabled(False)
        self.le_fatherName.setGeometry(QtCore.QRect(100, 110, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_fatherName.sizePolicy().hasHeightForWidth())
        self.le_fatherName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_fatherName.setFont(font)
        self.le_fatherName.setMaxLength(32)
        self.le_fatherName.setObjectName("le_fatherName")
        self.label_16 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_16.setGeometry(QtCore.QRect(5, 370, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.assignSchemeGB)
        self.label_17.setGeometry(QtCore.QRect(5, 400, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.showSchemeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.showSchemeGB.setGeometry(QtCore.QRect(330, 0, 1031, 681))
        self.showSchemeGB.setObjectName("showSchemeGB")
        
        self.tbl_assignScheme = QtWidgets.QTableWidget(self.showSchemeGB)
        self.tbl_assignScheme.setGeometry(QtCore.QRect(10, 70, 1011, 601))
        self.tbl_assignScheme.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_assignScheme.setRowCount(19)
        self.tbl_assignScheme.setColumnCount(8)
        self.tbl_assignScheme.setHorizontalHeaderLabels(['id','Title', 'Start Date', 'End Date', 'Due Date',
                                                         'Installments','Amount', 'Remarks'])
        self.tbl_assignScheme.setColumnHidden(0,True)
        self.tbl_assignScheme.setColumnWidth(1,210)
        self.tbl_assignScheme.setColumnWidth(4,55)
        self.tbl_assignScheme.setColumnWidth(5,65)
        self.tbl_assignScheme.setColumnWidth(6,50)
        self.tbl_assignScheme.setColumnWidth(7,400)
        self.tbl_assignScheme.setObjectName("tbl_assignScheme")
        
        self.filterGB = QtWidgets.QGroupBox(self.showSchemeGB)
        self.filterGB.setGeometry(QtCore.QRect(10, 20, 1011, 41))
        self.filterGB.setObjectName("filterGB")
        self.le_filterByName = QtWidgets.QLineEdit(self.filterGB)
        self.le_filterByName.setGeometry(QtCore.QRect(0, 20, 100, 20))
        self.le_filterByName.setObjectName("le_filterByName")
        self.le_filterByUserName = QtWidgets.QLineEdit(self.filterGB)
        self.le_filterByUserName.setGeometry(QtCore.QRect(110, 20, 100, 20))
        self.le_filterByUserName.setObjectName("le_filterByUserName")
        self.le_filterByCnic = QtWidgets.QLineEdit(self.filterGB)
        self.le_filterByCnic.setGeometry(QtCore.QRect(220, 20, 100, 20))
        self.le_filterByCnic.setObjectName("le_filterByCnic")
        self.le_filterByMobile = QtWidgets.QLineEdit(self.filterGB)
        self.le_filterByMobile.setGeometry(QtCore.QRect(330, 20, 100, 20))
        self.le_filterByMobile.setObjectName("le_filterByMobile")
        self.le_filterByAddress = QtWidgets.QLineEdit(self.filterGB)
        self.le_filterByAddress.setGeometry(QtCore.QRect(440, 20, 100, 20))
        self.le_filterByAddress.setObjectName("le_filterByAddress")
        self.btn_refresh = QtWidgets.QPushButton(self.filterGB)
        self.btn_refresh.setGeometry(QtCore.QRect(910, 10, 100, 28))
        refreshIcon = QtGui.QPixmap(globalVariables.Variables._icon+'refreshIcon.png')
        self.btn_refresh.setIcon(QtGui.QIcon(refreshIcon))
        self.btn_refresh.setObjectName("btn_refresh")
        self.btn_refresh.clicked.connect(self.showAssignedScheme)
        assignSchemeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(assignSchemeWindow)
        self.statusbar.setObjectName("statusbar")
        assignSchemeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(assignSchemeWindow)
        QtCore.QMetaObject.connectSlotsByName(assignSchemeWindow)

    def retranslateUi(self, assignSchemeWindow):
        _translate = QtCore.QCoreApplication.translate
        assignSchemeWindow.setWindowTitle(_translate("assignSchemeWindow", "Assign Scheme Window"))
        self.assignSchemeGB.setTitle(_translate("assignSchemeWindow", "Add New Installment"))
        self.btn_submit.setText(_translate("assignSchemeWindow", "Submit"))
        self.btn_cancel.setText(_translate("assignSchemeWindow", "Cancel"))
        self.label_11.setText(_translate("assignSchemeWindow", "Scheme"))
        self.le_balance.setPlaceholderText(_translate("assignSchemeWindow", "Current Balance"))
        self.le_installmentAmount.setPlaceholderText(_translate("assignSchemeWindow", "Installment Amount"))
        self.te_remarks.setPlaceholderText(_translate("assignSchemeWindow", "Remarks"))
        self.le_cellNo.setPlaceholderText(_translate("assignSchemeWindow", "Mobile"))
        self.label_12.setText(_translate("assignSchemeWindow", "Balance"))
        self.le_installments.setPlaceholderText(_translate("assignSchemeWindow", "Total Installments"))
        self.le_name.setPlaceholderText(_translate("assignSchemeWindow", "Name"))
        self.le_cnic.setPlaceholderText(_translate("assignSchemeWindow", "CNIC Number"))
        self.label_3.setText(_translate("assignSchemeWindow", "CNIC"))
        self.label_5.setText(_translate("assignSchemeWindow", "Address"))
        self.label_10.setText(_translate("assignSchemeWindow", "Account"))
        self.label_13.setText(_translate("assignSchemeWindow", "Amount"))
        self.le_installment.setPlaceholderText(_translate("assignSchemeWindow", "Paying Amount"))
        self.label_4.setText(_translate("assignSchemeWindow", "Cell No#"))
        self.te_address.setPlaceholderText(_translate("assignSchemeWindow", "Address"))
        self.label_6.setText(_translate("assignSchemeWindow", "Remarks"))
        self.label.setText(_translate("assignSchemeWindow", "Name"))
        self.label_14.setText(_translate("assignSchemeWindow", "Account Type"))
        self.label_15.setText(_translate("assignSchemeWindow", "Status"))
        self.le_status.setPlaceholderText(_translate("assignSchemeWindow", "Current Status"))
        self.label_2.setText(_translate("assignSchemeWindow", "S/O"))
        self.le_fatherName.setPlaceholderText(_translate("assignSchemeWindow", "Father Name"))
        self.label_16.setText(_translate("assignSchemeWindow", "Amount"))
        self.label_17.setText(_translate("assignSchemeWindow", "Installments"))
        self.showSchemeGB.setTitle(_translate("assignSchemeWindow", "All Installments"))
        self.filterGB.setTitle(_translate("assignSchemeWindow", "Filter"))
        self.le_filterByName.setPlaceholderText(_translate("assignSchemeWindow", "Search "))
        self.le_filterByUserName.setPlaceholderText(_translate("assignSchemeWindow", "Search "))
        self.le_filterByCnic.setPlaceholderText(_translate("assignSchemeWindow", "Search "))
        self.le_filterByMobile.setPlaceholderText(_translate("assignSchemeWindow", "Search "))
        self.le_filterByAddress.setPlaceholderText(_translate("assignSchemeWindow", "Search "))
        self.btn_refresh.setText(_translate("assignSchemeWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assignSchemeWindow = QtWidgets.QMainWindow()
    ui = Ui_assignSchemeWindow()
    ui.assignSchemeSetupUi(assignSchemeWindow)
    assignSchemeWindow.show()
    sys.exit(app.exec_())

