# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignSchemeConfirmForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Globals import globalVariables
from BLL.InstallmentsBL import assignSchemeBL

class Ui_assignSchemeConfirmDialog(object):
    _accountID = 0
    _schemeID = 0

    def setAssignSchemeFields(self,accountID, schemeID, name, cnic, cellno, scheme, amount, remarks):
        self._accountID = accountID
        self._schemeID = schemeID
        self.le_name.setText(name)
        self.le_cnic.setText(cnic)
        self.le_cellno.setText(cellno)
        self.le_scheme.setText(scheme)
        self.le_amount.setText(amount)
        self.te_remarks.setPlainText(remarks)

    def onConfirmAssign(self):
        assignSchemeBL.confirmAssignScheme(self._schemeID, self._accountID)

    def assignSchemeConfirmSetupUi(self, assignSchemeConfirmDialog):
        assignSchemeConfirmDialog.setObjectName("assignSchemeConfirmDialog")
        assignSchemeConfirmDialog.resize(327, 276)

        windowIcon = QtGui.QPixmap(globalVariables.Variables._icon+'logo.png')
        assignSchemeConfirmDialog.setWindowIcon(QtGui.QIcon(windowIcon))

        assignSchemeConfirmDialog.setStyleSheet(open(globalVariables.Variables._style,'r').read())
        assignSchemeConfirmDialog.setAutoFillBackground(True)

        self.conformAssignSchemeGB = QtWidgets.QGroupBox(assignSchemeConfirmDialog)
        self.conformAssignSchemeGB.setGeometry(QtCore.QRect(10, 0, 311, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conformAssignSchemeGB.sizePolicy().hasHeightForWidth())
        self.conformAssignSchemeGB.setSizePolicy(sizePolicy)
        self.conformAssignSchemeGB.setObjectName("conformAssignSchemeGB")
        self.le_name = QtWidgets.QLineEdit(self.conformAssignSchemeGB)
        self.le_name.setEnabled(False)
        self.le_name.setGeometry(QtCore.QRect(100, 20, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        self.le_name.setObjectName("le_name")
        self.le_scheme = QtWidgets.QLineEdit(self.conformAssignSchemeGB)
        self.le_scheme.setEnabled(False)
        self.le_scheme.setGeometry(QtCore.QRect(100, 110, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_scheme.sizePolicy().hasHeightForWidth())
        self.le_scheme.setSizePolicy(sizePolicy)
        self.le_scheme.setObjectName("le_scheme")
        self.le_cnic = QtWidgets.QLineEdit(self.conformAssignSchemeGB)
        self.le_cnic.setEnabled(False)
        self.le_cnic.setGeometry(QtCore.QRect(100, 50, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cnic.sizePolicy().hasHeightForWidth())
        self.le_cnic.setSizePolicy(sizePolicy)
        self.le_cnic.setObjectName("le_cnic")
        self.label = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.le_cellno = QtWidgets.QLineEdit(self.conformAssignSchemeGB)
        self.le_cellno.setEnabled(False)
        self.le_cellno.setGeometry(QtCore.QRect(100, 80, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cellno.sizePolicy().hasHeightForWidth())
        self.le_cellno.setSizePolicy(sizePolicy)
        self.le_cellno.setObjectName("le_cellno")
        self.le_amount = QtWidgets.QLineEdit(self.conformAssignSchemeGB)
        self.le_amount.setEnabled(False)
        self.le_amount.setGeometry(QtCore.QRect(100, 140, 200, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_amount.sizePolicy().hasHeightForWidth())
        self.le_amount.setSizePolicy(sizePolicy)
        self.le_amount.setObjectName("le_amount")
        self.label_6 = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.te_remarks = QtWidgets.QTextEdit(self.conformAssignSchemeGB)
        self.te_remarks.setEnabled(False)
        self.te_remarks.setGeometry(QtCore.QRect(100, 170, 200, 71))
        self.te_remarks.setObjectName("te_remarks")
        self.label_7 = QtWidgets.QLabel(self.conformAssignSchemeGB)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.conformAssignSchemeGB)
        self.buttonBox.setGeometry(QtCore.QRect(150, 240, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(assignSchemeConfirmDialog)
        self.buttonBox.accepted.connect(self.onConfirmAssign)
        self.buttonBox.accepted.connect(assignSchemeConfirmDialog.accept)
        self.buttonBox.rejected.connect(assignSchemeConfirmDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(assignSchemeConfirmDialog)

    def retranslateUi(self, assignSchemeConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        assignSchemeConfirmDialog.setWindowTitle(_translate("assignSchemeConfirmDialog", "Confirm Assgin Scheme"))
        self.conformAssignSchemeGB.setTitle(_translate("assignSchemeConfirmDialog", "Confirm Assign Scheme"))
        self.label.setText(_translate("assignSchemeConfirmDialog", "Name"))
        self.label_2.setText(_translate("assignSchemeConfirmDialog", "Scheme"))
        self.label_4.setText(_translate("assignSchemeConfirmDialog", "CNIC"))
        self.label_5.setText(_translate("assignSchemeConfirmDialog", "Cell No"))
        self.label_6.setText(_translate("assignSchemeConfirmDialog", "Amount"))
        self.label_7.setText(_translate("assignSchemeConfirmDialog", "Remarks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assignSchemeConfirmDialog = QtWidgets.QDialog()
    ui = Ui_assignSchemeConfirmDialog()
    ui.assignSchemeConfirmSetupUi(assignSchemeConfirmDialog)
    assignSchemeConfirmDialog.show()
    sys.exit(app.exec_())

