# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSchemeForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtPrintSupport

class Ui_schemeWindow(object):

    def print_widget(self):

        printer = QtPrintSupport.QPrinter()
        painter = QtGui.QPainter()
        painter.begin(printer)
        #Grab the widget here.. in our code, it will be ALWAYS centeral widget.
        screen = self.centralwidget.grab()
        painter.drawPixmap(10, 10, screen)
        painter.end()

    def setupUi(self, schemeWindow):
        schemeWindow.setObjectName("schemeWindow")
        schemeWindow.resize(1373, 723)
        self.centralwidget = QtWidgets.QWidget(schemeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addSchemeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.addSchemeGB.setEnabled(True)
        self.addSchemeGB.setGeometry(QtCore.QRect(10, 0, 311, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addSchemeGB.sizePolicy().hasHeightForWidth())
        self.addSchemeGB.setSizePolicy(sizePolicy)
        self.addSchemeGB.setObjectName("addSchemeGB")
        self.btn_submit = QtWidgets.QPushButton(self.addSchemeGB)
        self.btn_submit.setGeometry(QtCore.QRect(200, 640, 100, 28))
        self.btn_submit.setObjectName("btn_submit")
        self.btn_cancel = QtWidgets.QPushButton(self.addSchemeGB)
        self.btn_cancel.setGeometry(QtCore.QRect(100, 640, 100, 28))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_11 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_11.setGeometry(QtCore.QRect(10, 25, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.le_scheme = QtWidgets.QLineEdit(self.addSchemeGB)
        self.le_scheme.setEnabled(True)
        self.le_scheme.setGeometry(QtCore.QRect(100, 25, 200, 28))
        self.le_scheme.setObjectName("le_scheme")
        self.le_installments = QtWidgets.QLineEdit(self.addSchemeGB)
        self.le_installments.setEnabled(True)
        self.le_installments.setGeometry(QtCore.QRect(100, 165, 200, 28))
        self.le_installments.setObjectName("le_installments")
        self.label_13 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.le_installment = QtWidgets.QLineEdit(self.addSchemeGB)
        self.le_installment.setGeometry(QtCore.QRect(100, 200, 200, 28))
        self.le_installment.setObjectName("le_installment")
        self.label_6 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_6.setGeometry(QtCore.QRect(10, 235, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.te_remarks = QtWidgets.QTextEdit(self.addSchemeGB)
        self.te_remarks.setEnabled(True)
        self.te_remarks.setGeometry(QtCore.QRect(100, 235, 200, 71))
        self.te_remarks.setObjectName("te_remarks")
        self.label_12 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_12.setGeometry(QtCore.QRect(10, 165, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.le_startDate = QtWidgets.QLineEdit(self.addSchemeGB)
        self.le_startDate.setEnabled(False)
        self.le_startDate.setGeometry(QtCore.QRect(100, 60, 170, 28))
        self.le_startDate.setObjectName("le_startDate")
        self.le_endDate = QtWidgets.QLineEdit(self.addSchemeGB)
        self.le_endDate.setEnabled(False)
        self.le_endDate.setGeometry(QtCore.QRect(100, 95, 170, 28))
        self.le_endDate.setObjectName("le_endDate")
        self.label_15 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_15.setGeometry(QtCore.QRect(10, 95, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.btn_startDate = QtWidgets.QPushButton(self.addSchemeGB)
        self.btn_startDate.setGeometry(QtCore.QRect(270, 60, 30, 28))
        self.btn_startDate.setText("")
        self.btn_startDate.setObjectName("btn_startDate")
        self.btn_endDate = QtWidgets.QPushButton(self.addSchemeGB)
        self.btn_endDate.setGeometry(QtCore.QRect(270, 95, 30, 28))
        self.btn_endDate.setText("")
        self.btn_endDate.setObjectName("btn_endDate")
        self.sb_dueDate = QtWidgets.QSpinBox(self.addSchemeGB)
        self.sb_dueDate.setGeometry(QtCore.QRect(100, 130, 200, 28))
        self.sb_dueDate.setMinimum(1)
        self.sb_dueDate.setMaximum(31)
        self.sb_dueDate.setObjectName("sb_dueDate")
        self.label_16 = QtWidgets.QLabel(self.addSchemeGB)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.cw_startCalendar = QtWidgets.QCalendarWidget(self.addSchemeGB)
        self.cw_startCalendar.setGeometry(QtCore.QRect(0, 120, 312, 183))
        self.cw_startCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.cw_startCalendar.setObjectName("cw_startCalendar")
        self.cw_endCalendar = QtWidgets.QCalendarWidget(self.addSchemeGB)
        self.cw_endCalendar.setGeometry(QtCore.QRect(0, 90, 312, 183))
        self.cw_endCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.cw_endCalendar.setObjectName("cw_endCalendar")
        self.showSchemeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.showSchemeGB.setGeometry(QtCore.QRect(330, 0, 1031, 681))
        self.showSchemeGB.setObjectName("showSchemeGB")
        self.tbl_scheme = QtWidgets.QTableWidget(self.showSchemeGB)
        self.tbl_scheme.setGeometry(QtCore.QRect(10, 70, 1011, 601))
        self.tbl_scheme.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_scheme.setRowCount(19)
        self.tbl_scheme.setColumnCount(7)
        self.tbl_scheme.setObjectName("tbl_scheme")
        self.filterAccountGB = QtWidgets.QGroupBox(self.showSchemeGB)
        self.filterAccountGB.setGeometry(QtCore.QRect(10, 20, 1011, 41))
        self.filterAccountGB.setObjectName("filterAccountGB")
        self.le_filterByName = QtWidgets.QLineEdit(self.filterAccountGB)
        self.le_filterByName.setGeometry(QtCore.QRect(0, 20, 100, 20))
        self.le_filterByName.setObjectName("le_filterByName")
        self.le_filterByUserName = QtWidgets.QLineEdit(self.filterAccountGB)
        self.le_filterByUserName.setGeometry(QtCore.QRect(110, 20, 100, 20))
        self.le_filterByUserName.setObjectName("le_filterByUserName")
        self.le_filterByCnic = QtWidgets.QLineEdit(self.filterAccountGB)
        self.le_filterByCnic.setGeometry(QtCore.QRect(220, 20, 100, 20))
        self.le_filterByCnic.setObjectName("le_filterByCnic")
        self.le_filterByMobile = QtWidgets.QLineEdit(self.filterAccountGB)
        self.le_filterByMobile.setGeometry(QtCore.QRect(330, 20, 100, 20))
        self.le_filterByMobile.setObjectName("le_filterByMobile")
        self.le_filterByAddress = QtWidgets.QLineEdit(self.filterAccountGB)
        self.le_filterByAddress.setGeometry(QtCore.QRect(440, 20, 100, 20))
        self.le_filterByAddress.setObjectName("le_filterByAddress")
        self.btn_refresh = QtWidgets.QPushButton(self.filterAccountGB)
        self.btn_refresh.setGeometry(QtCore.QRect(910, 10, 100, 28))
        self.btn_refresh.setObjectName("btn_refresh")
        self.btn_refresh.clicked.connect(self.print_widget)
        schemeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(schemeWindow)
        self.statusbar.setObjectName("statusbar")
        schemeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(schemeWindow)
        QtCore.QMetaObject.connectSlotsByName(schemeWindow)

    def retranslateUi(self, schemeWindow):
        _translate = QtCore.QCoreApplication.translate
        schemeWindow.setWindowTitle(_translate("schemeWindow", "Add Scheme Window"))
        self.addSchemeGB.setTitle(_translate("schemeWindow", "Add New Scheme"))
        self.btn_submit.setText(_translate("schemeWindow", "Submit"))
        self.btn_cancel.setText(_translate("schemeWindow", "Cancel"))
        self.label_11.setText(_translate("schemeWindow", "Scheme"))
        self.label_13.setText(_translate("schemeWindow", "Amount"))
        self.label_6.setText(_translate("schemeWindow", "Remarks"))
        self.label_12.setText(_translate("schemeWindow", "Installments"))
        self.label_14.setText(_translate("schemeWindow", "Start Date"))
        self.label_15.setText(_translate("schemeWindow", "End Date"))
        self.label_16.setText(_translate("schemeWindow", "Due Date"))
        self.showSchemeGB.setTitle(_translate("schemeWindow", "All scheme"))
        self.filterAccountGB.setTitle(_translate("schemeWindow", "Filter"))
        self.btn_refresh.setText(_translate("schemeWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    schemeWindow = QtWidgets.QMainWindow()
    ui = Ui_schemeWindow()
    ui.setupUi(schemeWindow)
    schemeWindow.show()
    sys.exit(app.exec_())

