
from PyQt5 import QtCore, QtGui, QtWidgets
from Globals import globalVariables
from BLL.SaleBL import saleBL


class Ui_confirmSaleDialog(object):
    _accountId = 0
    _refAccountId = 0
    _imageCode = ''
    _itemList = []

    _policyType = ''
    _policyList = []

    def setConfirmSaleFields(self, date, invoice, accountId, accountName, accountCnic, accountMobile, accountAddress, refAccountId, refAccount,
                             company, product, engine,chassis, amount, discount,netAmount, payment, balance,
                             imageCode, itemList, policyType, policyList ):
        self.lbl_date.setText(date)
        self.lbl_invoice.setText(str(invoice[0]))

        self._accountId = accountId

        self._refAccountId = refAccountId
        if(refAccount != ''):
            refAccount = str(refAccount).split('-')
            self.lbl_refMobile.setText(refAccount[0])
            self.lbl_reference.setText(refAccount[1].upper())

        self.lbl_name.setText(accountName.upper())
        self.lbl_cnic.setText(accountCnic)
        self.lbl_mobileNo.setText(accountMobile)
        self.lbl_address.setText(accountAddress.upper())
        self.lbl_company.setText(company.upper())
        self.lbl_product.setText(product.upper())
        self.lbl_engine.setText(engine)
        self.lbl_chassis.setText(chassis)
        self.lbl_totalBill.setText(amount)
        self.lbl_discount.setText(discount)
        self.lbl_netBill.setText(netAmount)
        self.lbl_payment.setText(payment)
        self.lbl_balance.setText(balance)

        self._imageCode = imageCode
        self._itemList = itemList
        self._policyType = policyType
        self._policyList = policyList


    def onConfirmSale(self):
        accountId = self._accountId
        refAccountId = self._refAccountId
        date = self.lbl_date.text()
        totalBill = self.lbl_totalBill.text()
        discount = self.lbl_discount.text()
        netBill = self.lbl_netBill.text()
        payment = self.lbl_payment.text()
        balance = self.lbl_balance.text()
        imageCode = self._imageCode
        itemList = self._itemList
        policyType = self._policyType
        policyList = self._policyList


        saleBL.confirmSale(accountId, refAccountId, date, totalBill, discount, netBill, payment, balance, imageCode, itemList,
                              policyType, policyList)

    def confirmSaleSetupUi(self, confirmSaleDialog):
        confirmSaleDialog.setObjectName("confirmSaleDialog")
        confirmSaleDialog.resize(720, 410)

        windowIcon = QtGui.QPixmap(globalVariables.Variables._icon+'logo.png')
        confirmSaleDialog.setWindowIcon(QtGui.QIcon(windowIcon))

        confirmSaleDialog.setStyleSheet(open(globalVariables.Variables._style,'r').read())
        confirmSaleDialog.setAutoFillBackground(True)

        self.buttonBox = QtWidgets.QDialogButtonBox(confirmSaleDialog)
        self.buttonBox.setGeometry(QtCore.QRect(440, 380, 271, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.confirmSaleGB = QtWidgets.QGroupBox(confirmSaleDialog)
        self.confirmSaleGB.setGeometry(QtCore.QRect(10, 0, 700, 381))
        self.confirmSaleGB.setTitle("")
        self.confirmSaleGB.setObjectName("confirmSaleGB")
        self.lbl_header = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_header.setGeometry(QtCore.QRect(0, 10, 700, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.lbl_headerAddress = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_headerAddress.setGeometry(QtCore.QRect(0, 30, 700, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_headerAddress.setFont(font)
        self.lbl_headerAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_headerAddress.setObjectName("lbl_headerAddress")
        self.lbl_headerCellno = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_headerCellno.setGeometry(QtCore.QRect(0, 50, 700, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_headerCellno.setFont(font)
        self.lbl_headerCellno.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_headerCellno.setObjectName("lbl_headerCellno")
        self.label = QtWidgets.QLabel(self.confirmSaleGB)
        self.label.setGeometry(QtCore.QRect(10, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_2.setGeometry(QtCore.QRect(460, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_4.setGeometry(QtCore.QRect(460, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_address = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_address.setGeometry(QtCore.QRect(90, 130, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_address.setFont(font)
        self.lbl_address.setText("")
        self.lbl_address.setObjectName("lbl_address")
        self.lbl_cnic = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_cnic.setGeometry(QtCore.QRect(540, 110, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_cnic.setFont(font)
        self.lbl_cnic.setText("")
        self.lbl_cnic.setObjectName("lbl_cnic")
        self.lbl_mobileNo = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_mobileNo.setGeometry(QtCore.QRect(540, 130, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_mobileNo.setFont(font)
        self.lbl_mobileNo.setText("")
        self.lbl_mobileNo.setObjectName("lbl_mobileNo")
        self.lbl_name = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_name.setGeometry(QtCore.QRect(90, 110, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setText("")
        self.lbl_name.setObjectName("lbl_name")
        self.label_5 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_5.setGeometry(QtCore.QRect(460, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lbl_invoice = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_invoice.setGeometry(QtCore.QRect(540, 90, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_invoice.setFont(font)
        self.lbl_invoice.setText("")
        self.lbl_invoice.setObjectName("lbl_invoice")
        self.label_6 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lbl_date = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_date.setGeometry(QtCore.QRect(90, 90, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_date.setFont(font)
        self.lbl_date.setText("")
        self.lbl_date.setObjectName("lbl_date")
        self.label_9 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_9.setGeometry(QtCore.QRect(10, 350, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lbl_company = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_company.setGeometry(QtCore.QRect(90, 200, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_company.setFont(font)
        self.lbl_company.setText("")
        self.lbl_company.setObjectName("lbl_company")
        self.label_8 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_8.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lbl_product = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_product.setGeometry(QtCore.QRect(90, 220, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_product.setFont(font)
        self.lbl_product.setText("")
        self.lbl_product.setObjectName("lbl_product")
        self.lbl_chassis = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_chassis.setGeometry(QtCore.QRect(540, 220, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_chassis.setFont(font)
        self.lbl_chassis.setText("")
        self.lbl_chassis.setObjectName("lbl_chassis")
        self.label_11 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_11.setGeometry(QtCore.QRect(460, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_12.setGeometry(QtCore.QRect(460, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lbl_engine = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_engine.setGeometry(QtCore.QRect(540, 200, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_engine.setFont(font)
        self.lbl_engine.setText("")
        self.lbl_engine.setObjectName("lbl_engine")
        self.lbl_discount = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_discount.setGeometry(QtCore.QRect(90, 280, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_discount.setFont(font)
        self.lbl_discount.setText("")
        self.lbl_discount.setObjectName("lbl_discount")
        self.label_13 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_13.setGeometry(QtCore.QRect(10, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lbl_totalBill = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_totalBill.setGeometry(QtCore.QRect(90, 260, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_totalBill.setFont(font)
        self.lbl_totalBill.setText("")
        self.lbl_totalBill.setObjectName("lbl_totalBill")
        self.label_15 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_15.setGeometry(QtCore.QRect(10, 300, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lbl_netBill = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_netBill.setGeometry(QtCore.QRect(90, 300, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_netBill.setFont(font)
        self.lbl_netBill.setText("")
        self.lbl_netBill.setObjectName("lbl_netBill")
        self.label_16 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_16.setGeometry(QtCore.QRect(460, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.lbl_balance = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_balance.setGeometry(QtCore.QRect(540, 280, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_balance.setFont(font)
        self.lbl_balance.setText("")
        self.lbl_balance.setObjectName("lbl_balance")
        self.label_17 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_17.setGeometry(QtCore.QRect(460, 260, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lbl_payment = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_payment.setGeometry(QtCore.QRect(540, 260, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_payment.setFont(font)
        self.lbl_payment.setText("")
        self.lbl_payment.setObjectName("lbl_payment")
        self.label_18 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_18.setGeometry(QtCore.QRect(10, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lbl_reference = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_reference.setGeometry(QtCore.QRect(90, 160, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_reference.setFont(font)
        self.lbl_reference.setText("")
        self.lbl_reference.setObjectName("lbl_reference")
        self.label_19 = QtWidgets.QLabel(self.confirmSaleGB)
        self.label_19.setGeometry(QtCore.QRect(460, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lbl_refMobile = QtWidgets.QLabel(self.confirmSaleGB)
        self.lbl_refMobile.setGeometry(QtCore.QRect(540, 160, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_refMobile.setFont(font)
        self.lbl_refMobile.setText("")
        self.lbl_refMobile.setObjectName("lbl_refMobile")
        self.btn_print = QtWidgets.QPushButton(confirmSaleDialog)
        self.btn_print.setGeometry(QtCore.QRect(480, 385, 75, 23))
        self.btn_print.setObjectName("btn_print")

        self.retranslateUi(confirmSaleDialog)
        self.buttonBox.accepted.connect(self.onConfirmSale)
        self.buttonBox.accepted.connect(confirmSaleDialog.accept)
        self.buttonBox.rejected.connect(confirmSaleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(confirmSaleDialog)

    def retranslateUi(self, confirmSaleDialog):
        _translate = QtCore.QCoreApplication.translate
        confirmSaleDialog.setWindowTitle(_translate("confirmSaleDialog", "Confirm Sale Window"))
        self.lbl_header.setText(_translate("confirmSaleDialog", globalVariables.Variables._companyName))
        self.lbl_headerAddress.setText(_translate("confirmSaleDialog", globalVariables.Variables._compnayAddress))
        self.lbl_headerCellno.setText(_translate("confirmSaleDialog", globalVariables.Variables._compnayMobile))
        self.label.setText(_translate("confirmSaleDialog", "Customer :"))
        self.label_2.setText(_translate("confirmSaleDialog", "Mobile No :"))
        self.label_3.setText(_translate("confirmSaleDialog", "Address :"))
        self.label_4.setText(_translate("confirmSaleDialog", "CNIC :"))
        self.label_5.setText(_translate("confirmSaleDialog", "Invoice :"))
        self.label_6.setText(_translate("confirmSaleDialog", "Date :"))
        self.label_9.setText(_translate("confirmSaleDialog", "Signature : _________________"))
        self.label_8.setText(_translate("confirmSaleDialog", "Company :"))
        self.label_10.setText(_translate("confirmSaleDialog", "Product :"))
        self.label_11.setText(_translate("confirmSaleDialog", "Chassis :"))
        self.label_12.setText(_translate("confirmSaleDialog", "Engine :"))
        self.label_13.setText(_translate("confirmSaleDialog", "Discount :"))
        self.label_14.setText(_translate("confirmSaleDialog", "Total Bill :"))
        self.label_15.setText(_translate("confirmSaleDialog", "Net Bill :"))
        self.label_16.setText(_translate("confirmSaleDialog", "Un Paid :"))
        self.label_17.setText(_translate("confirmSaleDialog", "Paid :"))
        self.label_18.setText(_translate("confirmSaleDialog", "Reference :"))
        self.label_19.setText(_translate("confirmSaleDialog", "Ref-Mobile :"))
        self.btn_print.setText(_translate("confirmSaleDialog", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirmSaleDialog = QtWidgets.QDialog()
    ui = Ui_confirmSaleDialog()
    ui.confirmSaleSetupUi(confirmSaleDialog)
    confirmSaleDialog.show()
    sys.exit(app.exec_())

